---
kind: pipeline
type: docker
name: test-pr

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: identify-runner
  image: alpine:3.13
  commands:
  - echo $DRONE_RUNNER_NAME

- name: clone
  image: grafana/build-container:1.4.1
  commands:
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v0.5.48/grabpl
  - chmod +x bin/grabpl
  - git clone "https://$${GITHUB_TOKEN}@github.com/grafana/grafana-enterprise.git"
  - cd grafana-enterprise
  - git checkout ${ENTERPRISE_BRANCH}
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
    ENTERPRISE_BRANCH: master

- name: initialize
  image: grafana/build-container:1.4.1
  commands:
  - mv bin/grabpl /tmp/
  - rmdir bin
  - mv grafana-enterprise /tmp/
  - /tmp/grabpl init-enterprise /tmp/grafana-enterprise
  - mkdir bin
  - mv /tmp/grabpl bin/
  - ./bin/grabpl verify-drone
  - curl -fLO https://github.com/jwilder/dockerize/releases/download/v$${DOCKERIZE_VERSION}/dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - tar -C bin -xzvf dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - rm dockerize-linux-amd64-v$${DOCKERIZE_VERSION}.tar.gz
  - yarn install --frozen-lockfile --no-progress
  environment:
    DOCKERIZE_VERSION: 0.6.1
  depends_on:
  - clone

- name: lint-backend
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl lint-backend --edition enterprise
  environment:
    CGO_ENABLED: 1
  depends_on:
  - initialize

- name: codespell
  image: grafana/build-container:1.4.1
  commands:
  - "echo -e \"unknwon\nreferer\nerrorstring\neror\niam\nwan\" > words_to_ignore.txt"
  - codespell -I words_to_ignore.txt docs/
  depends_on:
  - initialize

- name: shellcheck
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl shellcheck
  depends_on:
  - initialize

- name: test-backend
  image: grafana/build-container:1.4.1
  commands:
  - "[ $(grep FocusConvey -R pkg | wc -l) -eq \"0\" ] || exit 1"
  - ./bin/grabpl test-backend --edition enterprise
  - ./bin/grabpl integration-tests --edition enterprise
  depends_on:
  - initialize
  - lint-backend

- name: test-frontend
  image: grafana/build-container:1.4.1
  commands:
  - yarn run ci:test-frontend
  environment:
    TEST_MAX_WORKERS: 50%
  depends_on:
  - initialize

- name: build-backend
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl build-backend --jobs 8 --edition enterprise --build-id ${DRONE_BUILD_NUMBER} --variants linux-x64,linux-x64-musl,osx64,win64 --no-pull-enterprise
  depends_on:
  - initialize
  - lint-backend
  - test-backend

- name: build-frontend
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl build-frontend --jobs 8 --no-install-deps --edition enterprise --build-id ${DRONE_BUILD_NUMBER} --no-pull-enterprise
  depends_on:
  - initialize
  - test-frontend

- name: build-plugins
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl build-plugins --jobs 8 --edition enterprise --no-install-deps
  depends_on:
  - initialize
  - lint-backend

- name: benchmark-ldap
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/dockerize -wait tcp://ldap:389 -timeout 120s
  - go test -benchmem -run=^$ ./pkg/extensions/ldapsync -bench "^(Benchmark50Users)$"
  environment:
    LDAP_HOSTNAME: ldap
  depends_on:
  - initialize

- name: lint-backend-enterprise2
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl lint-backend --edition enterprise2
  environment:
    CGO_ENABLED: 1
  depends_on:
  - initialize

- name: test-backend-enterprise2
  image: grafana/build-container:1.4.1
  commands:
  - "[ $(grep FocusConvey -R pkg | wc -l) -eq \"0\" ] || exit 1"
  - ./bin/grabpl test-backend --edition enterprise2
  - ./bin/grabpl integration-tests --edition enterprise2
  depends_on:
  - initialize
  - lint-backend-enterprise2

- name: build-backend-enterprise2
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl build-backend --jobs 8 --edition enterprise2 --build-id ${DRONE_BUILD_NUMBER} --variants linux-x64 --no-pull-enterprise
  depends_on:
  - initialize
  - lint-backend-enterprise2
  - test-backend-enterprise2

- name: gen-version
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/grabpl gen-version --build-id ${DRONE_BUILD_NUMBER}
  depends_on:
  - build-backend
  - build-frontend
  - build-plugins
  - test-backend
  - test-frontend
  - codespell
  - shellcheck
  - build-backend-enterprise2
  - test-backend-enterprise2

- name: package
  image: grafana/build-container:1.4.1
  commands:
  - . scripts/build/gpg-test-vars.sh && ./bin/grabpl package --jobs 8 --edition enterprise --build-id ${DRONE_BUILD_NUMBER} --no-pull-enterprise --variants linux-x64,linux-x64-musl,osx64,win64
  depends_on:
  - gen-version

- name: end-to-end-tests-server
  image: grafana/build-container:1.4.1
  detach: true
  commands:
  - ./e2e/start-server
  environment:
    PACKAGE_FILE: dist/grafana-enterprise-*linux-amd64.tar.gz
    PORT: 3001
    RUNDIR: e2e/tmp-grafana-enterprise
  depends_on:
  - package

- name: end-to-end-tests
  image: grafana/ci-e2e:12.19.0-1
  commands:
  - ./node_modules/.bin/cypress install
  - ./bin/grabpl e2e-tests --port 3001
  environment:
    HOST: end-to-end-tests-server
  depends_on:
  - end-to-end-tests-server

- name: build-storybook
  image: grafana/build-container:1.4.1
  commands:
  - yarn storybook:build
  - ./bin/grabpl verify-storybook
  environment:
    NODE_OPTIONS: --max_old_space_size=4096
  depends_on:
  - package

- name: build-frontend-docs
  image: grafana/build-container:1.4.1
  commands:
  - ./scripts/ci-reference-docs-lint.sh ci
  depends_on:
  - build-frontend

- name: build-docs-website
  image: grafana/docs-base:latest
  commands:
  - mkdir -p /hugo/content/docs/grafana
  - cp -r docs/sources/* /hugo/content/docs/grafana/latest/
  - cd /hugo && make prod
  depends_on:
  - initialize
  - build-frontend-docs

- name: copy-packages-for-docker
  image: grafana/build-container:1.4.1
  commands:
  - ls dist/*.tar.gz*
  - cp dist/*.tar.gz* packaging/docker/
  depends_on:
  - package

- name: build-docker-images
  image: grafana/drone-grafana-docker:0.3.2
  settings:
    archs: amd64
    dry_run: true
    edition: enterprise
  depends_on:
  - copy-packages-for-docker

- name: postgres-integration-tests
  image: grafana/build-container:1.4.1
  commands:
  - apt-get update
  - apt-get install -yq postgresql-client
  - ./bin/dockerize -wait tcp://postgres:5432 -timeout 120s
  - psql -p 5432 -h postgres -U grafanatest -d grafanatest -f devenv/docker/blocks/postgres_tests/setup.sql
  - go clean -testcache
  - ./bin/grabpl integration-tests --database postgres
  environment:
    GRAFANA_TEST_DB: postgres
    PGPASSWORD: grafanatest
    POSTGRES_HOST: postgres
  depends_on:
  - test-backend
  - test-frontend

- name: mysql-integration-tests
  image: grafana/build-container:1.4.1
  commands:
  - apt-get update
  - apt-get install -yq default-mysql-client
  - ./bin/dockerize -wait tcp://mysql:3306 -timeout 120s
  - cat devenv/docker/blocks/mysql_tests/setup.sql | mysql -h mysql -P 3306 -u root -prootpass
  - go clean -testcache
  - ./bin/grabpl integration-tests --database mysql
  environment:
    GRAFANA_TEST_DB: mysql
    MYSQL_HOST: mysql
  depends_on:
  - test-backend
  - test-frontend

- name: redis-integration-tests
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/dockerize -wait tcp://redis:6379/0 -timeout 120s
  - ./bin/grabpl integration-tests
  environment:
    REDIS_URL: redis://redis:6379/0
  depends_on:
  - test-backend
  - test-frontend

- name: memcached-integration-tests
  image: grafana/build-container:1.4.1
  commands:
  - ./bin/dockerize -wait tcp://memcached:11211 -timeout 120s
  - ./bin/grabpl integration-tests
  environment:
    MEMCACHED_HOSTS: memcached:11211
  depends_on:
  - test-backend
  - test-frontend

- name: package-enterprise2
  image: grafana/build-container:1.4.1
  commands:
  - . scripts/build/gpg-test-vars.sh && ./bin/grabpl package --jobs 8 --edition enterprise2 --build-id ${DRONE_BUILD_NUMBER} --no-pull-enterprise --variants linux-x64
  depends_on:
  - gen-version

- name: end-to-end-tests-server-enterprise2
  image: grafana/build-container:1.4.1
  detach: true
  commands:
  - ./e2e/start-server
  environment:
    PACKAGE_FILE: dist/grafana-enterprise2-*linux-amd64.tar.gz
    PORT: 3002
    RUNDIR: e2e/tmp-grafana-enterprise2
  depends_on:
  - package-enterprise2

- name: end-to-end-tests-enterprise2
  image: grafana/ci-e2e:12.19.0-1
  commands:
  - ./node_modules/.bin/cypress install
  - ./bin/grabpl e2e-tests --port 3002
  environment:
    HOST: end-to-end-tests-server-enterprise2
  depends_on:
  - end-to-end-tests-server-enterprise2

services:
- name: postgres
  image: postgres:12.3-alpine
  environment:
    POSTGRES_DB: grafanatest
    POSTGRES_PASSWORD: grafanatest
    POSTGRES_USER: grafanatest

- name: mysql
  image: mysql:5.6.48
  environment:
    MYSQL_DATABASE: grafana_tests
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_USER: grafana

- name: redis
  image: redis:6.2.1-alpine

- name: memcached
  image: memcached:1.6.9-alpine

- name: ldap
  image: osixia/openldap:1.4.0
  environment:
    LDAP_ADMIN_PASSWORD: grafana
    LDAP_DOMAIN: grafana.org
    SLAPD_ADDITIONAL_MODULES: memberof

trigger:
  branch:
  - master
  event:
  - push

...
